- name: install pip
  apt:
    name: python3-pip
    state: present

- name: install docker engine
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: pip install docker and docker-compose
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3

- name: Docker login to GitLab registry
  docker_login:
    registry_url: https://registry.gitlab.com
    username: "amaouchekaci28"
    password: "glpat-WPvKBSJ2PX-fd1_k4KQz"
    

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
