- name: install pip
  apt:
    name: python3-pip
    state: present
  become: yes

- name: install docker engine
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: pip install docker and docker-compose
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3
  become: yes

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
  become: yes

